# see https://github.com/compose-spec/compose-spec/blob/master/spec.md
# see https://github.com/opencontainers/image-spec/blob/master/annotations.md
services:
  tempo:
    # see https://hub.docker.com/r/grafana/tempo/tags
    # see https://github.com/grafana/tempo/releases
    image: grafana/tempo:2.3.1
    command:
      - -config.file=/etc/tempo/config.yml
    volumes:
      - ./tempo/config.yml:/etc/tempo/config.yml
    restart: on-failure
  grafana:
    # see https://hub.docker.com/r/grafana/grafana-oss/tags
    # see https://github.com/grafana/grafana/releases
    # see https://grafana.com/docs/grafana/latest/installation/docker/
    image: grafana/grafana-oss:10.0.11
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      # web-management.
      # http://localhost:3000
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: on-failure
  otelcol:
    # see https://hub.docker.com/r/otel/opentelemetry-collector-contrib/tags
    # see https://opentelemetry.io/docs/collector/installation/
    # see https://github.com/open-telemetry/opentelemetry-collector
    # see https://github.com/open-telemetry/opentelemetry-collector-contrib
    # see https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/examples/demo/docker-compose.yaml
    image: otel/opentelemetry-collector-contrib:0.94.0
    command:
      - --config=/etc/otelcol/config.yml
    ports:
      # otlp grpc.
      - 4317:4317
    volumes:
      - ./otelcol/config.yml:/etc/otelcol/config.yml
    restart: on-failure
  quotes:
    build: quotes
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - ASPNETCORE_URLS=http://+:8000
    ports:
      # http api.
      # http://localhost:8000
      - 8000:8000
    restart: on-failure
