# see https://prometheus.io/docs/operating/configuration/

global:
  scrape_interval: 15s    # Default is 1m.
  scrape_timeout: 10s     # Default is 10s.
  evaluation_interval: 1m # Default is 1m.

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
          - localhost:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: 
        - localhost:9090
  # TODO remove this depending on the outcome of the TODO otlp/prometheus
  #      defined in ../otelcol/config.yml.
  - job_name: otelcol
    static_configs:
      - targets:
        - otelcol:8889
