# see https://grafana.com/docs/grafana/latest/datasources/
# see https://grafana.com/docs/grafana/latest/datasources/tempo/

apiVersion: 1
datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
