# see https://grafana.com/docs/grafana/latest/administration/provisioning/
# see https://grafana.com/docs/grafana/latest/datasources/
# see https://grafana.com/docs/grafana/latest/datasources/alertmanager/
# see https://grafana.com/docs/grafana/latest/datasources/prometheus/
# see https://grafana.com/docs/grafana/latest/datasources/loki/
# see https://grafana.com/docs/grafana/latest/datasources/tempo/
# see https://grafana.com/docs/grafana/latest/datasources/tempo/configure-tempo-data-source/
# see https://grafana.com/docs/grafana/latest/explore/trace-integration/

apiVersion: 1
datasources:
  - name: Alertmanager
    type: alertmanager
    uid: alertmanager
    editable: true
    url: http://alertmanager:9093
    access: proxy
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: true
  - name: Prometheus
    type: prometheus
    uid: prometheus
    editable: true
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: '2.49.1'
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
  - name: Tempo
    type: tempo
    uid: tempo
    editable: true
    access: proxy
    url: http://tempo:3200
    isDefault: true
  - name: Loki
    type: loki
    uid: loki
    editable: true
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
