# see https://grafana.com/docs/grafana/latest/datasources/
# see https://grafana.com/docs/grafana/latest/datasources/loki/
# see https://grafana.com/docs/grafana/latest/datasources/tempo/
# see https://grafana.com/docs/grafana/latest/datasources/tempo/configure-tempo-data-source/
# see https://grafana.com/docs/grafana/latest/explore/trace-integration/

apiVersion: 1
datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
